In [34]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [35]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Kanniyakumari,8.08,77.57,81.14,80,59,8.68,IN,2020-10-27 14:42:09
1,1,Srednekolymsk,67.45,153.68,11.93,88,83,6.82,RU,2020-10-27 14:42:09
2,2,Clyde River,70.47,-68.59,9.90,84,49,3.87,CA,2020-10-27 14:40:05
3,3,Rocha,-34.48,-54.33,64.99,67,76,13.85,UY,2020-10-27 14:42:10
4,4,Busselton,-33.65,115.33,61.00,69,54,9.33,AU,2020-10-27 14:40:15
...,...,...,...,...,...,...,...,...,...,...
725,725,Fayaoue,-20.65,166.53,75.27,80,16,20.69,NC,2020-10-27 14:44:03
726,726,Colares,38.80,-9.45,64.99,63,75,10.29,PT,2020-10-27 14:44:03
727,727,Amboasary,-25.03,46.38,78.80,78,20,21.92,MG,2020-10-27 14:44:04
728,728,Pudozh,61.81,36.53,47.30,81,100,9.71,RU,2020-10-27 14:44:04
729,729,Santo Augusto,-27.85,-53.78,70.43,62,64,9.75,BR,2020-10-27 14:44:04

In [36]:
city_data_df.dtypes

City_ID         int64
City           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
Country        object
Date           object
dtype: object

In [37]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [38]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure()
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp],dissipating=False,max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [39]:
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

In [40]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [41]:
# Heatmap of percent Cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [42]:
# Heatmap of percent Wind Speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [43]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [45]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Kanniyakumari,8.08,77.57,81.14,80,59,8.68,IN,2020-10-27 14:42:09
6,6,Suba,10.84,121.01,83.59,78,97,18.21,PH,2020-10-27 14:42:10
11,11,Bauru,-22.31,-49.06,84.20,58,40,6.93,BR,2020-10-27 14:42:11
12,12,Srandakan,-7.94,110.25,77.27,88,100,3.74,ID,2020-10-27 14:42:11
13,13,Souillac,-20.52,57.52,77.00,69,40,9.17,MU,2020-10-27 14:42:11
25,25,Saint-Philippe,-21.36,55.77,77.00,69,0,4.70,RE,2020-10-27 14:41:57
26,26,Cabo San Lucas,22.89,-109.91,77.00,65,17,8.01,MX,2020-10-27 14:42:13
30,30,Saint-Joseph,-21.37,55.62,77.00,69,0,4.70,RE,2020-10-27 14:42:14
32,32,Tual,-5.67,132.75,82.96,77,86,9.48,ID,2020-10-27 14:42:14
35,35,Kampot,10.62,104.18,82.40,78,40,10.29,KH,2020-10-27 14:42:15

In [46]:
preferred_cities_df.dropna()
preferred_cities_df.dropna(axis='columns')

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Date
0,0,Kanniyakumari,8.08,77.57,81.14,80,59,8.68,2020-10-27 14:42:09
6,6,Suba,10.84,121.01,83.59,78,97,18.21,2020-10-27 14:42:10
11,11,Bauru,-22.31,-49.06,84.20,58,40,6.93,2020-10-27 14:42:11
12,12,Srandakan,-7.94,110.25,77.27,88,100,3.74,2020-10-27 14:42:11
13,13,Souillac,-20.52,57.52,77.00,69,40,9.17,2020-10-27 14:42:11
...,...,...,...,...,...,...,...,...,...
721,721,Impfondo,1.64,18.07,82.80,84,52,2.82,2020-10-27 14:44:03
723,723,Sampang,-7.19,113.24,82.36,73,100,2.89,2020-10-27 14:44:03
724,724,Aguada De Pasajeros,22.39,-80.85,84.20,83,75,5.82,2020-10-27 14:44:03
725,725,Fayaoue,-20.65,166.53,75.27,80,16,20.69,2020-10-27 14:44:03
727,727,Amboasary,-25.03,46.38,78.80,78,20,21.92,2020-10-27 14:44:04

In [47]:
preferred_cities_df.count()

City_ID       219
City          219
Lat           219
Lng           219
Max Temp      219
Humidity      219
Cloudiness    219
Wind Speed    219
Country       218
Date          219
dtype: int64

In [48]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

              City Country  Max Temp    Lat     Lng Hotel Name
0    Kanniyakumari      IN     81.14   8.08   77.57
6             Suba      PH     83.59  10.84  121.01
11           Bauru      BR     84.20 -22.31  -49.06
12       Srandakan      ID     77.27  -7.94  110.25
13        Souillac      MU     77.00 -20.52   57.52
25  Saint-Philippe      RE     77.00 -21.36   55.77
26  Cabo San Lucas      MX     77.00  22.89 -109.91
30    Saint-Joseph      RE     77.00 -21.37   55.62
32            Tual      ID     82.96  -5.67  132.75
35          Kampot      KH     82.40  10.62  104.18

In [49]:
city_weather = requests.get(city_url)

NameError: name 'city_url' is not defined

In [50]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [60]:
preferred_cities_df[["Lat","Lng"]]
params["location"] = f"{lat},{lng}"
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
hotels = requests.get(base_url, params=params).json()
try:
  hotel_df.loc[index,"Hotel Name"] = hotels["results"][0]["name"]
except (IndexError):
  print("Hotel not found... skipping.")
#print(hotels)
hotel_df.head(20)

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Kanniyakumari,IN,81.14,8.08,77.57,Sparsa
6,Suba,PH,83.59,10.84,121.01,Casita Bed and Grill
11,Bauru,BR,84.20,-22.31,-49.06,Astor Hotel
12,Srandakan,ID,77.27,-7.94,110.25,Puri Brata
13,Souillac,MU,77.00,-20.52,57.52,Bils' Villa
25,Saint-Philippe,RE,77.00,-21.36,55.77,"Chambres d'hÃ´te ""La TrinitÃ©"""
26,Cabo San Lucas,MX,77.00,22.89,-109.91,Hotel Tesoro Los Cabos
30,Saint-Joseph,RE,77.00,-21.37,55.62,"""Plantation Bed and Breakfast"
32,Tual,ID,82.96,-5.67,132.75,Grand Vilia Hotel
35,Kampot,KH,82.40,10.62,104.18,Champa Lodge
37,Nalut,LY,77.95,30.33,10.85,
38,Mareeba,AU,78.80,-17.00,145.43,Trinity Plains Tourist Park
40,Atuona,PF,78.21,-9.80,-139.03,Villa Enata
41,Mitu,CO,84.74,1.20,-70.17,
43,Soyo,AO,84.20,-6.13,12.37,Hotel Mpampa
48,Grand Gaube,MU,75.99,-20.01,57.66,Veranda Paul et Virginie Hotel & Spa
51,Tagcatong,PH,78.46,9.00,125.26,SKYâ€™S FLOATING COTTAGES
56,Kapaa,US,78.04,22.08,-159.32,Sheraton Kauai Resort at Coconut Beach
57,San Juan,AR,84.72,-31.54,-68.54,Hotel Provincial
58,Dingle,PH,77.79,11.00,122.67,Camp Pasica

In [59]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    #print(hotels)
    try:
     hotel_df.loc[index,"Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
     print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [53]:
hotel_df.head(20)

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Kanniyakumari,IN,81.14,8.08,77.57,Sparsa
6,Suba,PH,83.59,10.84,121.01,Casita Bed and Grill
11,Bauru,BR,84.20,-22.31,-49.06,Astor Hotel
12,Srandakan,ID,77.27,-7.94,110.25,Puri Brata
13,Souillac,MU,77.00,-20.52,57.52,Bils' Villa
25,Saint-Philippe,RE,77.00,-21.36,55.77,"Chambres d'hÃ´te ""La TrinitÃ©"""
26,Cabo San Lucas,MX,77.00,22.89,-109.91,Hotel Tesoro Los Cabos
30,Saint-Joseph,RE,77.00,-21.37,55.62,"""Plantation Bed and Breakfast"
32,Tual,ID,82.96,-5.67,132.75,Grand Vilia Hotel
35,Kampot,KH,82.40,10.62,104.18,Champa Lodge
37,Nalut,LY,77.95,30.33,10.85,
38,Mareeba,AU,78.80,-17.00,145.43,Trinity Plains Tourist Park
40,Atuona,PF,78.21,-9.80,-139.03,Villa Enata
41,Mitu,CO,84.74,1.20,-70.17,
43,Soyo,AO,84.20,-6.13,12.37,Hotel Mpampa
48,Grand Gaube,MU,75.99,-20.01,57.66,Veranda Paul et Virginie Hotel & Spa
51,Tagcatong,PH,78.46,9.00,125.26,SKYâ€™S FLOATING COTTAGES
56,Kapaa,US,78.04,22.08,-159.32,Sheraton Kauai Resort at Coconut Beach
57,San Juan,AR,84.72,-31.54,-68.54,Hotel Provincial
58,Dingle,PH,77.79,11.00,122.67,Camp Pasica

In [30]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [31]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [32]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))